# Generated by Django 4.2.2 on 2023-07-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_sem2_subdet_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem2_subdet',
            name='attendance',
            field=models.CharField(max_length=100),
        ),
    ]
