# Generated by Django 4.2.2 on 2023-07-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_sem2_subdet_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sem2_subdet',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='sem2_subdet',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='im1',
            field=models.CharField(default=123, max_length=100),
        ),
        migrations.DeleteModel(
            name='sem2_sub',
        ),
        migrations.DeleteModel(
            name='Sem2_subdet',
        ),
    ]
