# Generated by Django 4.2.2 on 2023-07-07 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0006_remove_sem2_subdet_sub_remove_sem2_subdet_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sem2_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(default=123, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sem2_subdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default=123, max_length=100)),
                ('attendance', models.CharField(default=123, max_length=100)),
                ('sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.sem2_sub')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
