# Generated by Django 4.2.2 on 2023-07-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_sem2_subdet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sem2_subdet',
            name='classes_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sem2_subdet',
            name='total_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='sem2_subdet',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.sem2_sub'),
        ),
    ]
