# Generated by Django 4.2.2 on 2023-07-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_sem2_subdet_total_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sem2_subdet',
            name='sub_code',
            field=models.CharField(default=123, max_length=100),
        ),
    ]
