# Generated by Django 4.2.2 on 2023-07-09 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0011_sem2_subdet_sub_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='sem1_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(default=123, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sem1_subdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(default=123, max_length=100)),
                ('grade', models.CharField(default=123, max_length=100)),
                ('attendance', models.CharField(default=123, max_length=100)),
                ('total_classes', models.IntegerField(default=100)),
                ('classes_present', models.IntegerField(default=0)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.sem2_sub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
