# Generated by Django 4.2.2 on 2023-07-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_sem1_subdet_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='sem1_subdet',
            name='Internals',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='sem1_subdet',
            name='P1',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='sem1_subdet',
            name='P2',
            field=models.IntegerField(default=30),
        ),
    ]
