# Generated by Django 4.2.2 on 2023-07-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_sem1_subdet_internals_sem1_subdet_p1_sem1_subdet_p2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sem1_subdet',
            old_name='Internals',
            new_name='internals',
        ),
        migrations.AddField(
            model_name='sem2_subdet',
            name='P1',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='sem2_subdet',
            name='P2',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='sem2_subdet',
            name='internals',
            field=models.IntegerField(default=10),
        ),
    ]
